class AddDeterminism < Formula
  desc "Build postprocessor to reset metadata fields for build reproducibility"
  homepage "https://github.com/keszybz/add-determinism"
  url "https://github.com/keszybz/add-determinism/archive/refs/tags/v0.7.2.tar.gz"
  sha256 "232c4f9fdc482dee5e6d38ef45a2c983b88283fe23d6ff4bcb26164b4c9a2dcb"
  license "GPL-3.0-or-later"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_linux:  "156a326176b8dcbc4c3969437aac756a6dcb34f783e645b75cd7024f93677d4d"
    sha256 cellar: :any_skip_relocation, x86_64_linux: "767dc6d4f1508e275358111572148658c5e6a2c1cf43a4eac965c3d659d2ef4e"
  end

  depends_on "llvm" => :build
  depends_on "pkgconf" => :build
  depends_on "rust" => :build
  depends_on "libselinux"
  depends_on :linux
  depends_on "zlib"

  def install
    ENV["RUSTFLAGS"] = "-C link-arg=-lselinux"
    system "cargo", "install", *std_cargo_args
  end

  test do
    (testpath/"test.html").write <<~EOS
      <!-- Generated by javadoc (1.2.3) on 2025-01-01 -->
      <meta name="dc.created" content="2025-01-01">
    EOS

    ENV["SOURCE_DATE_EPOCH"] = "0"
    system bin/"add-det", testpath/"test.html"

    assert_match "<!-- Generated by javadoc -->", (testpath/"test.html").read
    assert_match "content=\"1970-01-01\"", (testpath/"test.html").read
  end
end
