class Keploy < Formula
  desc "Testing Toolkit creates test-cases and data mocks from API calls, DB queries"
  homepage "https://keploy.io"
  url "https://github.com/keploy/keploy/archive/refs/tags/v2.10.5.tar.gz"
  sha256 "adea7dd557269277933961d0e04a1a679384eba9e0f92e18dc226212d485cc88"
  license "Apache-2.0"
  head "https://github.com/keploy/keploy.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "21fb99d675114f10ccf7da2cb485c7091e422422a625aaa41ba13ba3ba47ba74"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "21fb99d675114f10ccf7da2cb485c7091e422422a625aaa41ba13ba3ba47ba74"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "21fb99d675114f10ccf7da2cb485c7091e422422a625aaa41ba13ba3ba47ba74"
    sha256 cellar: :any_skip_relocation, sonoma:        "9223b6cb1f38bca006ea911323baf56f5012029f9601875d6eaa2d8479d2c03e"
    sha256 cellar: :any_skip_relocation, ventura:       "9223b6cb1f38bca006ea911323baf56f5012029f9601875d6eaa2d8479d2c03e"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "ce886d1ebf5e516db676e6caf34604624b0c95cb9b33c9109615593016a48fb2"
  end

  depends_on "go" => :build

  def install
    system "go", "build", *std_go_args(ldflags: "-s -w -X main.version=#{version}")
  end

  test do
    system bin/"keploy", "config", "--generate", "--path", testpath
    assert_match "# Generated by Keploy", (testpath/"keploy.yml").read

    output = shell_output("#{bin}/keploy templatize --path #{testpath}")
    assert_match "No test sets found to templatize", output

    assert_match version.to_s, shell_output("#{bin}/keploy --version")
  end
end
