class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.7.22.tar.gz"
  sha256 "d61929e4a54d8d3c02a0eccdab726d73b8f48176a19007d01ae27f9d5af0c8f5"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "55af79dab750ff18f5f61e23864b48e47f0c50fc844fc3a6394146ea93e7fd38"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "0991c97d1c5a298d504bca00e2342b4b3b4d022a5e4b25b8f3b03e6edea42993"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "5728ff7d475fa6116a443009de5a6b009f15c24d005beaed5030a02d1ca5177f"
    sha256 cellar: :any_skip_relocation, sonoma:        "58f089875358499b5fc68e363c9216351aa604085c49ed902357f2557010807b"
    sha256 cellar: :any_skip_relocation, ventura:       "2017e3c6d1a3c2ef25fe7a0f1e5f5f0e8e1339c56ca08371dca94dbbf69bfea6"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "2f966f1486d7cd512656be8dfd8a85ee4f476ac3134c2eb8a3f47407a3971f5d"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "c35bf4f8eb6068c7a2bc7e284be9c77ff97fcb11b93d0ad284e83fe3dbc0d6f2"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
