class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.8.22.tar.gz"
  sha256 "105d85f025378e0ac0284dc2e661139a3977dec3e4db1d32cec692de37c54bbd"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    sha256 cellar: :any_skip_relocation, arm64_tahoe:   "f9e3b5753265bf6dbbc03a28275f44b38a64b9d9a0514db2fecd7e43fe938a47"
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "aacaffd7254f2ba0744a8c883a98b55656579d0eced5038570684fb3a92b520d"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "36c35b8f892e62e9da7149946a7b8f4b3b815ea430cb334b7bc46cdadbd57ad8"
    sha256 cellar: :any_skip_relocation, sonoma:        "a05d964c712c54d9d53995fc13cde0b6329b02e7234ea9d88e00c56fcec6b49e"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "426c7cb730248702d22f19857020eb2a2e3e69de101b7c3df715e5e024021917"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "c4ed17a5f12dd3c4fba970eee35bbf3b9289679858d47e8f56dee98c0e48fa43"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
