class Uv < Formula
  desc "Extremely fast Python package installer and resolver, written in Rust"
  homepage "https://docs.astral.sh/uv/"
  url "https://github.com/astral-sh/uv/archive/refs/tags/0.8.12.tar.gz"
  sha256 "b6f86b547ea3744ffd14f14f07ccdfb60528ce7396a454a65ad72556272a0e67"
  license any_of: ["Apache-2.0", "MIT"]
  head "https://github.com/astral-sh/uv.git", branch: "main"

  bottle do
    rebuild 1
    sha256 cellar: :any_skip_relocation, arm64_sequoia: "76f7c27a2a1f20fca096428b77c2056ef8c354156590cd545f414dfb551df7b6"
    sha256 cellar: :any_skip_relocation, arm64_sonoma:  "7178b2cc2c4d67bd86bc4ed194b0ee7c9a2b54ac2a3701a953a9a6470e869c57"
    sha256 cellar: :any_skip_relocation, arm64_ventura: "76461de520202297f0335d3dc21448f6bc7e66f5918170e111708a75cf312b66"
    sha256 cellar: :any_skip_relocation, sonoma:        "068e8eaec4c489b2e00698d08fb9f5c1d8be0b09e69f4bc10adf409dcb273ea1"
    sha256 cellar: :any_skip_relocation, ventura:       "daa32c25465b8c273ebccf449f72c4887c16bb6a7f3bab320fd1739e48ae6347"
    sha256 cellar: :any_skip_relocation, arm64_linux:   "24b0d2aa0adde0a45b7df52eeddf5566a003e644dcf783d7b3993b45d991afd3"
    sha256 cellar: :any_skip_relocation, x86_64_linux:  "8f097f70e90569b7d4827b79155cf27538e329ff279d7e4d31be4f09a2ab01d6"
  end

  depends_on "pkgconf" => :build
  depends_on "rust" => :build

  uses_from_macos "python" => :test
  uses_from_macos "bzip2"
  uses_from_macos "xz"

  def install
    ENV["UV_COMMIT_HASH"] = ENV["UV_COMMIT_SHORT_HASH"] = tap.user
    ENV["UV_COMMIT_DATE"] = time.strftime("%F")
    # See: https://github.com/astral-sh/uv/issues/15401
    ENV["JEMALLOC_SYS_WITH_LG_PAGE"] = "16" if Hardware::CPU.arm? && OS.linux?
    system "cargo", "install", *std_cargo_args(path: "crates/uv")
    generate_completions_from_executable(bin/"uv", "generate-shell-completion")
    generate_completions_from_executable(bin/"uvx", "--generate-shell-completion")
  end

  test do
    (testpath/"requirements.in").write <<~REQUIREMENTS
      requests
    REQUIREMENTS

    compiled = shell_output("#{bin}/uv pip compile -q requirements.in")
    assert_match "This file was autogenerated by uv", compiled
    assert_match "# via requests", compiled

    assert_match "ruff 0.5.1", shell_output("#{bin}/uvx -q ruff@0.5.1 --version")
  end
end
